// generated by `sqlx migrate build-script`
// https://docs.rs/sqlx/latest/sqlx/macro.migrate.html
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
}